version: '3.9'

services:
  roadrunner:
    container_name: roadrunner
    build:
      context: ./.docker/roadrunner
      args:
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION}
    ports:
      - 8080:8080
    working_dir: /var/www/
    volumes:
      - .:/var/www
      - logs:/var/www/logs
      - ./.docker/roadrunner/conf/rr.yaml:/etc/rr.yaml:ro
    depends_on:
      - db
    links:
      - "db:database"
    env_file:
      - ./.docker/roadrunner/conf/rr.env
