<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'settings' => 'get1',
  'subEntry1' => 'get2',
  'subEntry2' => 'get3',
  'App\\Data\\Protocols\\User\\UserUseCaseInterface' => 'get4',
  'subEntry3' => 'get5',
  'App\\Data\\Protocols\\Auth\\LoginServiceInterface' => 'get6',
  'subEntry4' => 'get7',
  'subEntry5' => 'get8',
  'App\\Data\\Protocols\\Auth\\SignUpServiceInterface' => 'get9',
  'subEntry6' => 'get10',
  'App\\Data\\Protocols\\Markers\\Downloader\\MarkerDownloaderServiceInterface' => 'get11',
  'subEntry7' => 'get12',
  'subEntry8' => 'get13',
  'subEntry9' => 'get14',
  'App\\Data\\Protocols\\Markers\\Store\\MarkerServiceStoreInterface' => 'get15',
  'subEntry10' => 'get16',
  'subEntry11' => 'get17',
  'subEntry12' => 'get18',
  'App\\Data\\Protocols\\AsymCrypto\\SignerInterface' => 'get19',
  'subEntry13' => 'get20',
  'subEntry14' => 'get21',
  'subEntry15' => 'get22',
  'App\\Data\\Protocols\\Media\\MediaCollectorInterface' => 'get23',
  'App\\Data\\Protocols\\Resources\\ResourcesDownloaderInterface' => 'get24',
  'subEntry16' => 'get25',
  'subEntry17' => 'get26',
  'subEntry18' => 'get27',
  'App\\Domain\\Repositories\\UserRepository' => 'get28',
  'App\\Domain\\Repositories\\AccountRepository' => 'get29',
  'subEntry19' => 'get30',
  'App\\Domain\\Repositories\\MuseumRepository' => 'get31',
  'subEntry20' => 'get32',
  'subEntry21' => 'get33',
  'App\\Domain\\Repositories\\MarkerRepositoryInterface' => 'get34',
  'subEntry22' => 'get35',
  'subEntry23' => 'get36',
  'App\\Domain\\Repositories\\SignatureTokenRepositoryInterface' => 'get37',
  'subEntry24' => 'get38',
  'App\\Domain\\Repositories\\SignatureTokenRetrieverInterface' => 'get39',
  'subEntry25' => 'get40',
  'Psr\\Log\\LoggerInterface' => 'get41',
  'S3DataTransfer\\Interfaces\\Download\\StreamCollectorInterface' => 'get42',
  'S3DataTransfer\\S3\\Zip\\S3StreamObjectsZipDownloader' => 'get43',
  'S3DataTransfer\\Interfaces\\Upload\\UploadCollectorInterface' => 'get44',
  'League\\OAuth2\\Client\\Provider\\Google' => 'get45',
  'Doctrine\\ORM\\EntityManagerInterface' => 'get46',
  'Cycle\\Database\\DatabaseManager' => 'get47',
  'connection' => 'get48',
  'App\\Presentation\\Actions\\Markers\\Utils\\PresignedUrlCreator' => 'get49',
  'App\\Infrastructure\\Persistence\\PersistenceUtils\\ItemsRetriever' => 'get50',
  'subEntry26' => 'get51',
);

    protected function get2()
    {
        return [
            'name' => 'slim-app',
            'path' => 'php://stdout',
            'level' => 100,
        ];
    }

    protected function get3()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): array {
            return [
                // if true, metadata caching is forcefully disabled
                'dev_mode' => \Core\functions\isDev(),
    
                // path where the compiled metadata info will be cached
                // make sure the path exists and it is writable
                'cache_dir' => \getcwd().'/var/doctrine',
    
                // you should add any other path containing annotated entity classes
                'metadata_dirs' => [\getcwd().'/src/Domain/Models'],
    
                'connection' => $c->get('connection'),
            ];
        }, 'subEntry2');
    }

    protected function get1()
    {
        return [
            'displayErrorDetails' => true,
            'logger' => $this->get2(),
            'doctrine' => $this->get3(),
        ];
    }

    protected function get5()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\UserRepository');
    }

    protected function get4()
    {
        $object = new App\Data\UseCases\User\UserService($this->get5());
        return $object;
    }

    protected function get7()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\AccountRepository');
    }

    protected function get8()
    {
        return $this->delegateContainer->get('App\\Data\\Protocols\\Cryptography\\ComparerInterface');
    }

    protected function get6()
    {
        $object = new App\Data\UseCases\Authentication\Login($this->get7(), $this->get8());
        return $object;
    }

    protected function get10()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\AccountRepository');
    }

    protected function get9()
    {
        $object = new App\Data\UseCases\Authentication\SignUp($this->get10());
        return $object;
    }

    protected function get12()
    {
        return $this->delegateContainer->get('S3DataTransfer\\S3\\Zip\\S3StreamObjectsZipDownloader');
    }

    protected function get13()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\MarkerRepositoryInterface');
    }

    protected function get14()
    {
        return $this->delegateContainer->get('App\\Data\\Protocols\\Media\\MediaCollectorInterface');
    }

    protected function get11()
    {
        $object = new App\Data\UseCases\Markers\MarkerDownloader($this->get12(), $this->get13(), $this->get14());
        return $object;
    }

    protected function get16()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\MuseumRepository');
    }

    protected function get17()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\MarkerRepositoryInterface');
    }

    protected function get18()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get15()
    {
        $object = new App\Data\UseCases\Markers\MarkerServiceStore($this->get16(), $this->get17(), $this->get18());
        return $object;
    }

    protected function get20()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\MuseumRepository');
    }

    protected function get21()
    {
        return $this->delegateContainer->get('App\\Data\\Protocols\\Cryptography\\AsymmetricEncrypter');
    }

    protected function get22()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\SignatureTokenRepositoryInterface');
    }

    protected function get19()
    {
        $object = new App\Data\UseCases\AsymCrypto\AsymmetricSigner($this->get20(), $this->get21(), $this->get22());
        return $object;
    }

    protected function get23()
    {
        $object = new App\Data\UseCases\Media\MediaCollectorVisitor();
        return $object;
    }

    protected function get25()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\MuseumRepository');
    }

    protected function get26()
    {
        return $this->delegateContainer->get('App\\Domain\\Repositories\\MarkerRepositoryInterface');
    }

    protected function get27()
    {
        return $this->delegateContainer->get('App\\Presentation\\Actions\\Markers\\Utils\\PresignedUrlCreator');
    }

    protected function get24()
    {
        $object = new App\Data\UseCases\Resources\DeliveryMan($this->get25(), $this->get26(), $this->get27());
        return $object;
    }

    protected function get28()
    {
        $object = new App\Infrastructure\Persistence\User\InMemoryUserRepository(NULL);
        return $object;
    }

    protected function get30()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get29()
    {
        $object = new App\Infrastructure\Persistence\Account\DoctrineAccountRepository($this->get30());
        return $object;
    }

    protected function get32()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get33()
    {
        return $this->delegateContainer->get('App\\Infrastructure\\Persistence\\PersistenceUtils\\ItemsRetriever');
    }

    protected function get31()
    {
        $object = new App\Infrastructure\Persistence\Museum\MuseumDoctrineRepository($this->get32(), $this->get33());
        return $object;
    }

    protected function get35()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get36()
    {
        return $this->delegateContainer->get('App\\Infrastructure\\Persistence\\PersistenceUtils\\ItemsRetriever');
    }

    protected function get34()
    {
        $object = new App\Infrastructure\Persistence\Marker\MarkerDoctrineRepository($this->get35(), $this->get36());
        return $object;
    }

    protected function get38()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get37()
    {
        $object = new App\Infrastructure\Persistence\SignatureToken\SignatureTokenRepository($this->get38());
        return $object;
    }

    protected function get40()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get39()
    {
        $object = new App\Infrastructure\Persistence\SignatureToken\SignatureTokenRepository($this->get40());
        return $object;
    }

    protected function get41()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $settings = $c->get('settings');

        $loggerSettings = $settings['logger'];
        $logger = new \Monolog\Logger($loggerSettings['name']);

        $processor = new \Monolog\Processor\UidProcessor();
        $logger->pushProcessor($processor);

        $handler = new \Monolog\Handler\StreamHandler($loggerSettings['path'], $loggerSettings['level']);
        $logger->pushHandler($handler);

        return $logger;
    }, 'Psr\\Log\\LoggerInterface');
    }

    protected function get42()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \S3DataTransfer\Interfaces\Download\StreamCollectorInterface {
        $factory = new \S3DataTransfer\S3\Factories\S3AsyncDownloaderFactory();
        $key = $_ENV['S3KEY'];
        $secret = $_ENV['S3SECRET'];
        $region = $_ENV['S3REGION'];
        $version = $_ENV['S3VERSION'];

        return $factory->create($key, $secret, $region, $version);
    }, 'S3DataTransfer\\Interfaces\\Download\\StreamCollectorInterface');
    }

    protected function get43()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $container): \S3DataTransfer\S3\Zip\S3StreamObjectsZipDownloader {
        /**
         * @var StreamCollectorInterface
         */
        $streamCollector = $container->get(\S3DataTransfer\Interfaces\Download\StreamCollectorInterface::class);

        return new \S3DataTransfer\S3\Zip\S3StreamObjectsZipDownloader($streamCollector);
    }, 'S3DataTransfer\\S3\\Zip\\S3StreamObjectsZipDownloader');
    }

    protected function get44()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \S3DataTransfer\Interfaces\Upload\UploadCollectorInterface {
        $factory = new \S3DataTransfer\S3\Factories\S3AsyncUploadingFactory();
        $key = $_ENV['S3KEY'];
        $secret = $_ENV['S3SECRET'];
        $region = $_ENV['S3REGION'];
        $version = $_ENV['S3VERSION'];

        return $factory->create($key, $secret, $region, $version);
    }, 'S3DataTransfer\\Interfaces\\Upload\\UploadCollectorInterface');
    }

    protected function get45()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): \League\OAuth2\Client\Provider\Google {
        $clientId = $_ENV['GOOGLE_CLIENT_ID'];
        $clientSecret = $_ENV['GOOGLE_CLIENT_SECRET'];
        $redirectUri = $_ENV['GOOGLE_REDIRECT_URI'];
        
        return new \League\OAuth2\Client\Provider\Google(\compact('clientId', 'clientSecret', 'redirectUri'));
    }, 'League\\OAuth2\\Client\\Provider\\Google');
    }

    protected function get46()
    {
        return $this->resolveFactory(static fn (
        \Psr\Container\ContainerInterface $container
    ) => \Core\Data\Doctrine\EntityManagerBuilder::produce(
        $container->get("settings")["doctrine"]
    ), 'Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get47()
    {
        return $this->resolveFactory(static function (
        \Psr\Container\ContainerInterface $container
    ): \Cycle\Database\DatabaseManager {
        $connectorFacade = new \Core\Data\Cycle\Facade\ConnectorFacade(
            connection: $container->get("connection")
        );

        // Configure connector as you wish
        $connectorFacade
            ->configureFactory()
            ->withQueryCache(true)
            ->withSchema("public");

        return new \Cycle\Database\DatabaseManager(
            new \Cycle\Database\Config\DatabaseConfig([
                "default" => "default",
                "databases" => [
                    "default" => ["connection" => "production"],
                ],
                "connections" => [
                    "sqlite" => new \Cycle\Database\Config\SQLiteDriverConfig(
                        connection: new \Cycle\Database\Config\SQLite\MemoryConnectionConfig(),
                        queryCache: true
                    ),
                    "production" => $connectorFacade->produceDriverConnection(),
                ],
            ])
        );
    }, 'Cycle\\Database\\DatabaseManager');
    }

    protected function get48()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c): array {
        $scanDatabase = function (): array {
            $connectionArray = [];

            if (isset($_ENV['DATABASE_URL'])) {
                $connectionArray['url'] = $_ENV['DATABASE_URL'];
            } else {
                $databaseSettings = ['DRIVER', 'HOST', 'DBNAME', 'PORT', 'USER', 'PASSWORD', 'CHARSET'];

                foreach ($databaseSettings as $value) {
                    $connectionArray[$value] = $_ENV[$value];
                }
            }

            return $connectionArray;
        };

        return match (\Core\functions\mode()) {
            'TEST' => [
                'driver' => 'pdo_sqlite',
                'memory' => 'true',
            ],
            'PRODUCTION', 'DEV' => $scanDatabase(),
            default => throw new \Exception(
                'An application mode should be specified at project level'
                . ' .env or _ENV variable and should contain one of the '
                . 'following values: PRODUCTION, TEST or DEV',
                500
            )
        };
    }, 'connection');
    }

    protected function get49()
    {
        $object = new App\Presentation\Actions\Markers\Utils\PresignedUrlCreator();
        return $object;
    }

    protected function get51()
    {
        return $this->delegateContainer->get('Doctrine\\ORM\\EntityManagerInterface');
    }

    protected function get50()
    {
        $object = new App\Infrastructure\Persistence\PersistenceUtils\ItemsRetriever($this->get51());
        return $object;
    }

}
