<?php

namespace App\Presentation\Actions\Protocols;

enum ErrorsEnum: string
{
    case BAD_REQUEST = 'BAD_REQUEST';

    case INSUFFICIENT_PRIVILEGES = 'INSUFFICIENT_PRIVILEGES';

    case NOT_ALLOWED = 'NOT_ALLOWED';

    case NOT_IMPLEMENTED = 'NOT_IMPLEMENTED';

    case RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';

    case SERVER_ERROR = 'SERVER_ERROR';

    case UNAUTHENTICATED = 'UNAUTHENTICATED';

    case VALIDATION_ERROR = 'VALIDATION_ERROR';

    case VERIFICATION_ERROR = 'VERIFICATION_ERROR';

    case UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY';
}